- name: Install Python pip
  hosts: all
  become: yes 
  tasks:
    - name: Ensure pip for Python 3 is installed
      ansible.builtin.dnf:
        name: python3-pip  
        state: present

    - name: Verify pip installation
      command: pip3 --version
      register: pip_version
      changed_when: false

    - name: Display pip version
      ansible.builtin.debug:
        msg: "Pip version installed: {{ pip_version.stdout }}"
