- name: Install Redis, Firewalld and Node Exporter
  hosts: all
  become: yes
  tasks:
    - name: Ensure Redis is installed
      ansible.builtin.dnf:
        name: redis
        state: present

    - name: Verify Redis installation
      command: redis-server --version
      register: redis_version
      changed_when: false

    - name: Display Redis version
      ansible.builtin.debug:
        msg: "Redis version installed: {{ redis_version.stdout }}"

    - name: Install firewalld
      ansible.builtin.dnf:
        name: firewalld
        state: present

    - name: Enable firewalld service
      ansible.builtin.systemd:
        name: firewalld
        enabled: yes

    - name: Start firewalld service
      ansible.builtin.systemd:
        name: firewalld
        state: started

    - name: Open HTTP service in the firewall
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes
        zone: public

    - name: accept repo GPG key
      ansible.builtin.shell:
        cmd: rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9

    - name: Install EPEL
      ansible.builtin.dnf:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        state: present

    - name: install node-exporter
      ansible.builtin.dnf:
        name: golang-github-prometheus-node-exporter
        state: latest

    - name: move service file
      ansible.builtin.copy:
        src: ./node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root

    - name: start node-exporter
      ansible.builtin.service:
        name: node_exporter
        state: started
        daemon_reload: true

    - name: open port 9100
      ansible.posix.firewalld:
        port: 9100/tcp
        permanent: true
        state: enabled
        zone: public
        immediate: true
        
    - name: Reload firewalld
      ansible.builtin.command:
        cmd: firewall-cmd --reload