- name: Install Python pip and Redis
  hosts: all
  become: yes
  tasks:
    - name: Ensure pip for Python 3 is installed
      ansible.builtin.dnf:
        name: python3-pip
        state: present

    - name: Verify pip installation
      command: pip3 --version
      register: pip_version
      changed_when: false

    - name: Display pip version
      ansible.builtin.debug:
        msg: "Pip version installed: {{ pip_version.stdout }}"

    - name: Ensure Redis is installed
      ansible.builtin.dnf:
        name: redis
        state: present

    - name: Verify Redis installation
      command: redis-server --version
      register: redis_version
      changed_when: false

    - name: Display Redis version
      ansible.builtin.debug:
        msg: "Redis version installed: {{ redis_version.stdout }}"
