---
- name: Setup for client nodes
  hosts: clients
  become: true
  tasks:
    - name: Activate blip_venv and perform tasks
      shell: |
        source ~/data/blip_venv/bin/activate
        cd ~/data/COMP0239-CW/pipelines/
        if [[ "{{ inventory_hostname }}" == "client" ]]; then
          redis-cli flushdb
        fi
        celery multi stop_verify worker --pidfile=celery.pid --logfile=celery.log
        celery -A app.celery worker --loglevel=info --pidfile=celery.pid --logfile=celery.log --concurrency=1 -D
      args:
        executable: /bin/bash

- name: Setup for host node
  hosts: host
  become: true
  tasks:
    - name: Activate blip_venv and run applications
      shell: |
        source ~/blip_venv/bin/activate
        cd ~/COMP0239-CW/pipelines/
        nohup celery -A app.celery flower --port=4505 &
        nohup prometheus --config.file=/etc/prometheus/prometheus.yml &
        nohup flask run --host=0.0.0.0 &
        nohup python test_pipelines.py &
      args:
        executable: /bin/bash
